# Generated by Django 2.2.15 on 2020-10-10 15:16

from decimal import Decimal
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Acoes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('desc_acao', models.CharField(max_length=150, null=True, verbose_name='Nome da Ação')),
            ],
        ),
        migrations.CreateModel(
            name='Objetivos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('desc_objetivo', models.CharField(max_length=350, verbose_name=False)),
            ],
        ),
        migrations.CreateModel(
            name='Responsaveis',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_responsavel', models.CharField(max_length=150, verbose_name='Nome')),
                ('contato_responsavel', models.EmailField(max_length=150, verbose_name='E-mail')),
            ],
        ),
        migrations.CreateModel(
            name='Temas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('desc_tema', models.CharField(max_length=150, verbose_name='Nome do Tema')),
            ],
        ),
        migrations.CreateModel(
            name='Tarefas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('realizado_tarefa', models.BooleanField(default=False, verbose_name='Concluída')),
                ('valor_financeiro_tarefa', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=20, verbose_name=False)),
                ('desc_tarefa', models.CharField(max_length=350, null=True, verbose_name=False)),
                ('acess_objetivo_tarefa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='test_models.Objetivos', verbose_name=False)),
            ],
        ),
        migrations.CreateModel(
            name='SubTarefas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('desc_subTarefa', models.CharField(max_length=150, verbose_name='Nome da SubTarefa')),
                ('realizado_subTarefa', models.BooleanField(default=False, verbose_name='Sub Tarefa realizada')),
                ('data_inicio_subtarefa', models.DateField(null=True, verbose_name='Data de Inicio')),
                ('data_fim_subtarefa', models.DateField(null=True, verbose_name='Data de Fim')),
                ('acess_responsaveis', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='test_models.Responsaveis')),
                ('acess_tarefas', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='test_models.Tarefas')),
            ],
        ),
        migrations.CreateModel(
            name='Projetos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('desc_projeto', models.CharField(max_length=150, verbose_name='Nome do Projeto')),
                ('valor_financeiro_projeto', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=20, verbose_name='Valor (Ex.: 100000)')),
                ('data_inicio_projeto', models.DateField(null=True, verbose_name='Data de Inicio (Ex.: dd/mm/yyyy)')),
                ('data_fim_projeto', models.DateField(null=True, verbose_name='Data de Fim (Ex.: dd/mm/yyyy)')),
                ('acess_acoes_projeto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='test_models.Acoes', verbose_name='Nome da Ação')),
                ('acess_responsaveis_projeto', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='test_models.Responsaveis', verbose_name='Responsável')),
                ('acess_temas_projeto', models.ForeignKey(default=True, on_delete=django.db.models.deletion.CASCADE, to='test_models.Temas', verbose_name='Nome do Tema')),
            ],
        ),
        migrations.AddField(
            model_name='objetivos',
            name='acess_projeto_objetivo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='test_models.Projetos', verbose_name='Projeto'),
        ),
    ]
