# Generated by Django 2.2.15 on 2020-10-09 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_auto_20200809_0120'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uniprotkb',
            name='length',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
